using JetBrains.Annotations;

namespace Typhon.Schema.Definition;

/// <summary>
/// Declares how a cluster-eligible archetype's <see cref="StorageMode.SingleVersion"/> component values reach disk, and therefore how much of them a crash may
/// lose. Set per archetype via <c>[Archetype(ClusterDurability = ...)]</c>; the default is <see cref="FenceWal"/>, which preserves the pre-existing behaviour.
/// </summary>
/// <remarks>
/// <para>
/// This is a knob on the durability axis (see <c>CommitDiscipline</c> and ADR-005), not the storage axis: it changes *when* values become durable, never the
/// cluster layout. It is deliberately per-ARCHETYPE and not per-component, because a cluster page interleaves every component of the archetype — page-granular
/// durability cannot express a per-component policy.
/// </para>
/// <para>
/// It applies only to <see cref="StorageMode.SingleVersion"/> values in the cluster. <see cref="StorageMode.Versioned"/> components are unaffected in every
/// setting: their revision chain is WAL-logged at commit and is authoritative, and the cluster HEAD is a cache rebuilt from it on reopen. Transaction
/// atomicity, lifecycle records (Spawn / Destroy / SetEnabledBits) and <c>CommitDiscipline.Commit</c> writes are likewise untouched.
/// </para>
/// <para>
/// Design: <c>claude/design/Durability/cluster-page-durability.md</c>. Issue #568.
/// </para>
/// </remarks>
[PublicAPI]
public enum ClusterDurability : byte
{
    /// <summary>
    /// Default, and the pre-#568 behaviour. Dirty SingleVersion values are written to the WAL at every tick fence.
    /// </summary>
    /// <remarks>
    /// ⚠️ The ≤1-tick loss window this is meant to provide is <b>nominal, not currently delivered</b>: crash recovery has no <c>ApplySlotToExisting</c>, so it
    /// discards these records for any entity that already existed at the last checkpoint — which in a steady-state simulation is effectively all of them. In
    /// practice such entities recover at checkpoint granularity, exactly like <see cref="Checkpoint"/>, while still paying the full WAL cost. Tracked by #569;
    /// until it is fixed, the only difference this setting makes for a pre-existing entity is the write amplification.
    /// </remarks>
    FenceWal = 0,

    /// <summary>
    /// No fence WAL records. SingleVersion values reach disk through the checkpoint — the same path cluster STRUCTURE (slot claim, occupancy, entity keys,
    /// growth) has always used. <b>A crash loses up to one checkpoint interval of value updates</b> (<c>ResourceOptions.CheckpointIntervalMs</c>, 30 s by
    /// default): the entities survive, their values are as of the last checkpoint.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Choose this for high-frequency simulation state that is regenerated by the simulation itself — position, velocity, AI scratch — where thirty seconds of
    /// staleness after a crash is cheaper than writing every tick. Do not choose it for state a player would notice losing; use
    /// <c>CommitDiscipline.Commit</c> or <see cref="StorageMode.Versioned"/> for that, both of which keep working normally alongside this setting.
    /// </para>
    /// <para>
    /// <b>Name the window, not the speed:</b> read this as "thirty seconds", not as "fast". The performance gain is a consequence of the weaker guarantee, not
    /// the guarantee itself.
    /// </para>
    /// </remarks>
    Checkpoint = 1,
}
