import { describe, expect, it } from 'vitest';
import { CatalogPlan, parseCatalog } from '../src/index.js';
import { goldenBin, goldenJson } from './golden-support.js';

/*
 * catalog-engine: the one vector the ENGINE emitted, from its compiled projection plan, rather than a hand-built
 * model. Every other catalog vector is written by `Typhon.Protocol.Tests` against the protocol library; this one comes
 * out of `CatalogBuilder` at Start, which is what a client will actually be handed in `WELCOME`. It is here so that
 * "the TypeScript SDK accepts what the server sends" is asserted against the server's own bytes and not against a
 * second author's idea of them.
 *
 * Regenerated by the C# side: `TYPHON_UPDATE_GOLDEN=1 dotnet test --filter CatalogBuilderTests`.
 */

interface CatalogVector {
  readonly hash: string;
  readonly byteCount: number;
}

describe('catalog-engine', () => {
  it('parses, validates and compiles the catalog the engine emits', () => {
    const bin = goldenBin('catalog-engine');
    expect(bin.length).toBe((goldenJson('catalog-engine') as CatalogVector).byteCount);

    // parseCatalog is the client's whole acceptance path: JSON, the validator, and the refusal of a catalog that is
    // valid but not canonical — an index or an order a decode plan would map to the wrong fields.
    const plan = CatalogPlan.compile(parseCatalog(bin));

    expect(plan.archetypes.map((a) => a.name)).toEqual(['ProjCreature', 'ProjPlayer', 'ProjRock']);

    const creature = plan.archetypeByName('ProjCreature')!;
    expect(creature.position!.dims).toBe(2);
    expect(creature.position!.linear).toBe(true);
    expect(creature.onEnter.fields.map((f) => f.name)).toEqual(['template']);
    expect(creature.groupSections.map((s) => s.fields.map((f) => f.name))).toEqual([
      ['alerted', 'mode'],
      ['hp', 'level'],
    ]);
    expect(creature.fields.find((f) => f.name === 'mode')!.enumNames).toEqual([
      'Idle',
      'Wander',
      'Chase',
      'Attack',
      'Dead',
    ]);

    // An owner section travels apart, with its own groups and its own bit space.
    const player = plan.archetypeByName('ProjPlayer')!;
    expect(player.ownerGroups).toEqual(['bag', 'owner']);
    expect(player.ownerSections.map((s) => s.fields.map((f) => f.name))).toEqual([['items'], ['credits']]);

    // A static archetype has no change group at all: every field is in the enter record.
    const rock = plan.archetypeByName('ProjRock')!;
    expect(rock.groupSections).toEqual([]);
    expect(rock.onEnter.fields.map((f) => f.name)).toEqual(['kind']);
    expect(rock.position!.linear).toBe(false);

    // Reserved ranges: the built-in at 0, the application's from 16 — whatever either side declares.
    expect(plan.clientRegion!.body.fields.map((f) => f.name)).toEqual(['altitudeM', 'budgetKiBps', 'vertices']);
    expect(plan.command(16).name).toBe('SwgMoveTo');
    expect(plan.command(17).name).toBe('SwgSetTarget');
    expect(plan.event(16).name).toBe('SwgAttack');

    // The eleven built-in metrics at 0-10, then the application's from 32. The two vector built-ins carry one value
    // per label; every other metric is a scalar.
    expect(plan.metrics.map((m) => m.idx)).toEqual([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 32]);
    expect(plan.metrics.find((m) => m.name === 'typhon.system.mean')!.valueCount).toBe(3);
    expect(plan.metrics.find((m) => m.name === 'typhon.archetype.entities')!.valueCount).toBe(3);
    expect(plan.sessionMetrics.map((m) => m.name)).toEqual([
      'typhon.session.outBytesPerSec',
      'typhon.session.skippedFrames',
      'typhon.session.droppedCommands',
    ]);

    // Phase 1 replicates no aggregate tier, so the engine declares no grid and no resume window.
    expect(plan.grids).toEqual([]);
    expect(plan.catalog.limits.resumeGraceMs).toBe(0);
  });
});
