#!/usr/bin/env sh
# Canonical docs build (local & CI): API from built assemblies, with the API
# landing woven into the generated toc, then the full site.
#
# Splitting docfx into metadata -> inject -> build (instead of one `docfx
# doc/docfx.json`) is required so scripts/inject-api-index.py can add the API
# landing to the regenerated api/toc.yml before the site is rendered.
#
# Usage: scripts/build-docs.sh [Debug|Release]   (default: Debug)
# Prereq: `dotnet build src/Typhon.Shell -c <config>` has run (for API assemblies).
set -eu
CONFIG="${1:-Debug}"

# Clean generated output first — DocFX's incremental build leaves orphaned HTML
# (and stale search-index / manifest entries) when a source page is deleted.
rm -rf doc/_site doc/obj
rm -f doc/api/*.yml doc/api/.manifest         # regenerated by metadata (keeps hand-authored api/index.md)

sh scripts/stage-api-bin.sh "$CONFIG"        # public DLLs + XML docs -> doc/.api-bin
dotnet docfx metadata doc/docfx.json          # -> doc/api/*.yml + api/toc.yml
python3 scripts/inject-api-index.py           # weave the API landing into api/toc.yml
dotnet docfx build doc/docfx.json             # -> doc/_site
echo "built doc/_site"
