using Typhon.Protocol;
using Typhon.Schema.Definition;

namespace SwgTatooine;

// ═══════════════════════════════════════════════════════════════════════════════════════════════════════════════════
// Archetypes
//
// Five, and the heterogeneity is the point. The engine's existing spatial workloads all run ONE archetype, which means
// the fence sees one population with one update rate and one durability policy. A game server sees nothing like that:
// its buildings never move and never tick, its creatures move on a slow AI cadence, its players move every tick and are
// the only things anyone queries around, and exactly one of its archetypes is worth a WAL record.
//
// ClusterDurability.Checkpoint on all five is the honest setting rather than a shortcut. A creature's position
// is regenerated by the simulation; writing it to the WAL ten times a second buys a guarantee nobody wants. Inventory
// is the exception and is Versioned, so the WAL is genuinely in the loop.
// ═══════════════════════════════════════════════════════════════════════════════════════════════════════════════════

/// <summary>
/// Everything placed and immobile: city buildings, terminals, shuttleports, point-of-interest props, player houses,
/// factories and harvesters.
/// </summary>
/// <remarks>
/// <para>By far the largest population on a real planet, and the one that costs the fence nothing per tick — provided
/// the fence is told it never moves. This archetype is what <c>SetSpatialBarrierOnly</c> exists for.</para>
/// <para>Factories and harvesters DO tick, on periods of seconds to minutes, but they tick their own counters rather
/// than their position, so the spatial layer never hears from them.</para>
/// </remarks>
[Archetype(1, "Static world objects", ClusterDurability = ClusterDurability.Checkpoint)]
[Replicated]
public partial class WorldObject : Archetype<WorldObject>
{
    [Position]
    public static readonly Comp<StructurePlacement> Bounds = Register<StructurePlacement>();
    public static readonly Comp<Structure> Struct = Register<Structure>();
    public static readonly Comp<StructureRealm> Realm = Register<StructureRealm>();
}

/// <summary>
/// A creature lair or a mission camp's spawner. Static like a <see cref="WorldObject"/>, but it holds state that changes
/// — a live count and a respawn timer — so it is walked every tick by the spawn system.
/// </summary>
[Archetype(1, "Creature lairs", ClusterDurability = ClusterDurability.Checkpoint)]
[Replicated]
public partial class CreatureLair : Archetype<CreatureLair>
{
    [Position]
    public static readonly Comp<LairPlacement> Bounds = Register<LairPlacement>();
    public static readonly Comp<Lair> Spawner = Register<Lair>();
    public static readonly Comp<LairVitals> Vitals = Register<LairVitals>();
    public static readonly Comp<LairRealm> Realm = Register<LairRealm>();
}

/// <summary>
/// A hostile or neutral creature: banthas, womp rats, Tusken Raiders, and the defenders of a destroy-mission camp.
/// Moves on the AI cadence, which is slower than the tick, and is the bulk of the moving population.
/// </summary>
[Archetype(1, "Creatures and hostile NPCs", ClusterDurability = ClusterDurability.Checkpoint)]
[Replicated]
public partial class Creature : Archetype<Creature>
{
    [Motion(ToleranceM = 0.05, TeleportMps = TatooineReplication.MaxSpeedMps)]
    public static readonly Comp<CreaturePlacement> Bounds = Register<CreaturePlacement>();
    public static readonly Comp<CreatureMotion> Move = Register<CreatureMotion>();
    public static readonly Comp<CreatureVitals> Vitals = Register<CreatureVitals>();
    public static readonly Comp<CreatureBrain> Ai = Register<CreatureBrain>();

    /// <summary>Scheduling only — deliberately NOT projected, so a write here reaches no subscriber. See <see cref="CreatureTimers"/>.</summary>
    public static readonly Comp<CreatureTimers> Timers = Register<CreatureTimers>();
    public static readonly Comp<CreatureRealm> Realm = Register<CreatureRealm>();
}

/// <summary>
/// A city NPC — vendor, trainer, mission-terminal attendant, ambient civilian. Overwhelmingly stationary, densely packed
/// inside city bounds, and never queried around. It exists because a real city's NPC population is a large, extremely
/// clumped, almost-static entity set, which is a distinct load shape from either the buildings or the creatures.
/// </summary>
[Archetype(1, "City NPCs", ClusterDurability = ClusterDurability.Checkpoint)]
[Replicated]
public partial class CityNpc : Archetype<CityNpc>
{
    [Motion(ToleranceM = 0.05, TeleportMps = TatooineReplication.MaxSpeedMps)]
    public static readonly Comp<NpcPlacement> Bounds = Register<NpcPlacement>();
    public static readonly Comp<NpcMotion> Move = Register<NpcMotion>();
    public static readonly Comp<NpcBrain> Ai = Register<NpcBrain>();

    /// <summary>Scheduling only — deliberately NOT projected. See <see cref="CreatureTimers"/>.</summary>
    public static readonly Comp<NpcTimers> Timers = Register<NpcTimers>();
    public static readonly Comp<NpcRealm> Realm = Register<NpcRealm>();
}

/// <summary>
/// An AI starship in the space realm (Realms G1c): the one deep-3D, f64 archetype. Not replicated yet (F1).
/// </summary>
[Archetype(1, "Starships", ClusterDurability = ClusterDurability.Checkpoint)]
public partial class Starship : Archetype<Starship>
{
    public static readonly Comp<ShipPlacement> Bounds = Register<ShipPlacement>();
    public static readonly Comp<ShipMotion> Move = Register<ShipMotion>();
    public static readonly Comp<ShipRealm> Realm = Register<ShipRealm>();
}

/// <summary>
/// A player character. The smallest population and the most expensive one: players move every tick, and every player is
/// the centre of an awareness query that has to find everything around it.
/// </summary>
/// <remarks>
/// Players carry <see cref="Inventory"/>, which is <see cref="StorageMode.Versioned"/> — so this archetype has BOTH a
/// checkpoint-durable cluster half and a WAL-logged versioned half. That mixture is the interesting case and it is why
/// the inventory lives on the player rather than in a table of its own.
/// </remarks>
[Archetype(1, "Players", ClusterDurability = ClusterDurability.Checkpoint)]
[Replicated]
public partial class Player : Archetype<Player>
{
    [Motion(TeleportMps = TatooineReplication.MaxSpeedMps)]
    public static readonly Comp<PlayerPlacement> Bounds = Register<PlayerPlacement>();
    public static readonly Comp<PlayerMotion> Move = Register<PlayerMotion>();
    public static readonly Comp<PlayerVitals> Vitals = Register<PlayerVitals>();
    public static readonly Comp<PlayerState> State = Register<PlayerState>();
    public static readonly Comp<Inventory> Inventory = Register<Inventory>();
    public static readonly Comp<PlayerRealm> Realm = Register<PlayerRealm>();
}
